import "dotenv/config";
import bodyParser from "body-parser";
import cors from "cors";
import express, { Request, Response } from "express";
import helmet from "helmet";
import morgan from "morgan";
import "reflect-metadata";
import swaggerJSDoc from "swagger-jsdoc";
import swaggerStats from "swagger-stats";
import swaggerUi from "swagger-ui-express";
import { createConnection } from "typeorm";
import routes from "./routes";

const options = {
  swaggerDefinition: {
    info: {
      title: "Test API",
      version: "1.0.0",
      description: "Test Express API with autogenerated swagger doc",
    },
  },
  apis: ["**/routes/auth.ts", "**/controller/Admin/*.ts"],
};

const specs = swaggerJSDoc(options);

createConnection()
  .then(() => {
    const app = express();

    // ---------------- MIDDLEWARES ----------------
    app.use(cors());
    app.use(helmet());

    // swagger stats
    app.use(swaggerStats.getMiddleware({}));

    // body parser
    app.use(bodyParser.json());

    // ---------------- MORGAN CUSTOM TOKENS ----------------
    morgan.token("header-auth", (req: Request) => {
      return req.headers["auth"] as string || "";
    });

    morgan.token("body", (req: Request) => {
      return JSON.stringify((req as any).body || {});
    });

    // ---------------- LOGGING ----------------
    app.use(
      morgan("[:date[web]] :method :url :remote-addr")
    );

    app.use(
      morgan("[:date[web]] token=:header-auth")
    );

    app.use(
      morgan("[:date[web]] body=:body")
    );

    app.use(
      morgan("[:date[iso]] :status :res[content-length] - :response-time ms")
    );

    // ---------------- ROUTES ----------------
    app.use("/", routes);

    // ---------------- SWAGGER ----------------
    app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));

    // ---------------- START SERVER ----------------
    app.listen(3000, () => {
      console.log("Server started on port 3000!");
    });
  })
  .catch((error) => {
    console.error("Database connection error:", error);
  });