import bodyParser from "body-parser";
import cors from "cors";
import express, { Request } from "express";
import helmet from "helmet";
import morgan from "morgan";
import "reflect-metadata";
import swaggerJSDoc from "swagger-jsdoc";
import swaggerStats from "swagger-stats";
import swaggerUi from "swagger-ui-express";
import { createConnection } from "typeorm";
import routes from "./routes";
import logger from "./utils/logger";
import { errorHandler } from "./middlewares/errorHandler";
import testRoutes from "./routes/test.routes";

const options = {
  swaggerDefinition: {
    info: {
      title: "Test API",
      version: "1.0.0",
      description: "Test Express API with autogenerated swagger doc",
    },
  },
  apis: ["**/routes/auth.ts", "**/controller/Admin/*.ts"],
};

const specs = swaggerJSDoc(options);

createConnection()
  .then(() => {
    const app = express();

    // ---------------- SECURITY MIDDLEWARES ----------------
    app.use(cors());
    app.use(helmet());

    // ---------------- SWAGGER STATS ----------------
    app.use(swaggerStats.getMiddleware({}));

    // ---------------- BODY PARSER ----------------
    app.use(bodyParser.json());

    // ---------------- MORGAN CUSTOM TOKENS ----------------
    morgan.token("body", (req: Request) => {
      return JSON.stringify((req as any).body || {});
    });

    morgan.token("auth-header", (req: Request) => {
      return (req.headers["authorization"] as string) || "";
    });

    // ---------------- MORGAN LOGGING (TERMINAL + FILE READY) ----------------
    app.use(
      morgan("[:date[iso]] :method :url :status :response-time ms - :remote-addr", {
        stream: {
          write: (msg) => logger.info(msg.trim()),
        },
      })
    );

    // Log request body (only for debugging, optional in production)
    app.use(
      morgan("BODY => :body", {
        stream: {
          write: (msg) => logger.info(msg.trim()),
        },
      })
    );

    // Log auth header (security tracking)
    app.use(
      morgan("AUTH => :auth-header", {
        stream: {
          write: (msg) => logger.info(msg.trim()),
        },
      })
    );

    // ---------------- ROUTES ----------------
    app.use("/", routes);

    // ---------------- TEST ROUTES (FOR DEMO) ----------------
    app.use("/test", testRoutes);

    // ---------------- SWAGGER DOCS ----------------
    app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));

    // ---------------- GLOBAL ERROR HANDLER ----------------
    app.use(errorHandler);

    // ---------------- START SERVER ----------------
    const PORT = Number(process.env.PORT) || 3000;
    app.listen(PORT, () => {
      logger.info(`Server started on port ${PORT}!`);
    });
  })
  .catch((error) => {
    logger.error("Database connection error", error);
  });